
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    expose:
      - 8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/data:/data
      - ./dist/scripts:/scripts
    depends_on:
      - server