events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        location / {
            root /data/www;
        }
        location /scripts/ {
            root /;
        }
        location /images/ {
            root /data;
        }
    }
}